### ISSUE TITLE
preprocess command input

### ISSUE THREAD

**Issue by tomthomas3000** [pouyaesm/signed-community-detection#2]
Thank you so much for making this package. I downloaded the jar file from the link within the README. I was wondering re: the input for the preprocess command. I have been able to the run the mdl command without issue.

The input '-c' for the preprocess command - is this meant to be the graph in format [id1 id2 weight] within a text file, or is it the partition.txt as per output of the mdl command? And what should the values for the other arguments look like? I would be grateful if you might be able to provide an example of a sample commands.

I used the following command:
java -jar signed-community-detection-1.1.1.jar preprocess -c graph.txt
java -jar signed-community-detection-1.1.1.jar preprocess -c partition.txt 

Both times I am getting the following error: "Parsing failed.  Reason: partition address is not specified". 

I tracked the error back through OperationCenter.java and PreProcess.java within the github, it would appear that line 32 of the PreProcess.java expects OperationCenter.INPUT_GRAPH. In OperationCenter.java, INPUT_GRAPH = "g", but "g" in preprocess command is the output-graph, hence doesn't seem related to the input.

I would be deeply grateful if you might be able to advise. Thank you.

**Comment by pouyaesm** [comment]
output-graph is now "-n" to avoid the conflict. -g is the input-graph address.
